name: Create Pull Request
description: Create pull request

inputs:
  # https://github.com/peter-evans/create-pull-request/blob/main/action.yml
  token:
    description: 'GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)'
    default: ${{ github.token }}
  body:
    description: 'The body of the pull request.'
    default: ''
  assignees:
    description: 'A comma or newline separated list of assignees (GitHub usernames).'
    default: |
      silver886
  reviewers:
    description: 'A comma or newline separated list of reviewers (GitHub usernames) to request a review from.'
    default: |
      silver886

runs:
  using: composite
  steps:
    - name: Get time
      id: time
      uses: silver886/github-actions/time@master
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ inputs.token }}
        branch: continuous-update/${{ steps.time.outputs.date }}
        branch-suffix: timestamp
        delete-branch: true
        commit-message: Update on ${{ steps.time.outputs.date }}
        title: Continuous update on ${{ steps.time.outputs.date }}
        body: |
          > Auto-generated by `create-pull-request`[^1].

          ${{ inputs.body }}

          [^1]: https://github.com/peter-evans/create-pull-request
        assignees: ${{ inputs.assignees }}
        reviewers: ${{ inputs.reviewers }}
