name: Create Release
description: Create release

inputs:
  # https://github.com/softprops/action-gh-release/blob/master/action.yml
  name:
    description: 'Gives the release a custom name. Defaults to tag name'
    required: false
  files:
    description: 'Newline-delimited list of path globs for asset files to upload'
    required: false
  body_path:
    description: 'Path to load note-worthy description of changes in release from'
    required: false

runs:
  using: composite
  steps:
    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ inputs.name }}
        preserve_order: true
        files: ${{ inputs.files }}
        body_path: ${{ inputs.body_path }}
