name: Time
description: Get current time

outputs:
  date:
    description: Current date
    value: ${{ steps.time.outputs.date }}
  time:
    description: Current time
    value: ${{ steps.time.outputs.time }}
  rfc3339:
    description: Current date and time in RFC3339 format
    value: ${{ steps.time.outputs.rfc3339 }}

runs:
  using: composite
  steps:
    - name: Get current date and time
      id: time
      shell: sh
      run: |
        echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        echo "time=$(date +'%T')" >> $GITHUB_OUTPUT
        echo "rfc3339=$(date +'%Y-%m-%dT%T%:z')" >> $GITHUB_OUTPUT
        date --rfc3339=seconds
        date --iso8601=seconds
