name: Create release

on:
  workflow_call:

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Create release
        uses: silver886/github-actions/create/release@master
        with:
          name: Release ${{ github.ref_name }}
