name: Release npm package

on:
  workflow_call:
    inputs:
      test:
        type: boolean
        default: true
    secrets:
      NPM:
        required: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        if: ${{ inputs.test }}
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        if: ${{ inputs.test }}
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true
      - name: Cache pnpm modules
        if: ${{ inputs.test }}
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Clean install dependencies
        if: ${{ inputs.test }}
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: |
            args: [--frozen-lockfile]
      - name: Test
        if: ${{ inputs.test }}
        run: pnpm test

  publish-github:
    name: Publish to GitHub Package Registry
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Clean install dependencies
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: |
            args: [--frozen-lockfile]
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          scope: ${{ github.repository_owner }}
          registry-url: https://npm.pkg.github.com/
      - name: Publish package
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}

  publish-npm:
    name: Publish to npm
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Clean install dependencies
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: |
            args: [--frozen-lockfile]
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          scope: ${{ github.repository_owner }}
          registry-url: https://registry.npmjs.org/
      - name: Publish package
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM }}
