name: Release npm package

on:
  workflow_call:
    inputs:
      test:
        description: Unit test
        type: boolean
        default: true
    secrets:
      NPM:
        required: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout code
        if: ${{ inputs.test }}
        uses: silver886/github-actions/checkout@master
      - name: Setup Node.js
        if: ${{ inputs.test }}
        uses: silver886/github-actions/setup/nodejs@master
      - name: Setup pnpm
        if: ${{ inputs.test }}
        uses: silver886/github-actions/setup/pnpm@master
      - name: Test
        if: ${{ inputs.test }}
        run: pnpm test

  publish-github:
    name: Publish to GitHub Package Registry
    needs: test
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: silver886/github-actions/checkout@master
      - name: Setup Node.js
        uses: silver886/github-actions/setup/nodejs@master
      - name: Setup pnpm
        uses: silver886/github-actions/setup/pnpm@master
      - name: Setup Node.js environment
        uses: silver886/github-actions/setup/nodejs@master
        with:
          scope: ${{ github.repository_owner }}
          registry-url: https://npm.pkg.github.com/
      - name: Publish package
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}

  publish-npm:
    name: Publish to npm
    needs: test
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: silver886/github-actions/checkout@master
      - name: Setup Node.js
        uses: silver886/github-actions/setup/nodejs@master
      - name: Setup pnpm
        uses: silver886/github-actions/setup/pnpm@master
      - name: Setup Node.js environment
        uses: silver886/github-actions/setup/nodejs@master
        with:
          scope: ${{ github.repository_owner }}
          registry-url: https://registry.npmjs.org/
      - name: Publish package
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM }}
